---
apiVersion: v1
kind: Service
metadata:
  name: stock-db-writer-test
spec:
  type: ClusterIP
  selector:
    app: stock-db-writer-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
